---
- hosts: all
  become: yes
  vars_files:
    - /home/ec2-user/devops11/sample
  tasks:
    - name: adding secrect to the file
      lineinfile: 
        path: /home/ec2-user/devops11/vault-pass.txt
        create: yes
        line: "{{password}}"
...
