- hosts: all
  become: yes
  vars:
    working_directory: /home/ec2-user/ansible-example
    packages:
    - httpd
    - java
    dict_test:
      name: devops
      batch: devops11
  tasks:
    - name: creating directory
      file:
        name: "{{ working_directory }}"
        state: directory
    - name: list variable example
      yum:
        name: "{{ packages }}"
    - name: dictionary variable
      command: ls "/home/ec2-user/{{dict_test['name']}}"
      register: output
    - name: display output
      debug:
        var: output

